# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: CIRelease
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch --all --tags

      - name: Create .gradle dir
        run: mkdir -p $HOME/.gradle

      - name: Install gpg secret key
        env:
          SIGNINGFILE: ${{ secrets.SIGNINGFILE }}
        run: |
          cat <(echo -e "${{ secrets.SIGNINGFILE }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Export gpg file
        env:
          SIGNINGKEYID: ${{ secrets.SIGNINGKEYID }}
          SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}
        run: |
          gpg --batch --passphrase="$SIGNINGPASSWORD" --pinentry-mode loopback --export-secret-keys $SIGNINGKEYID > $HOME/.gradle/secrets.gpg

      - name: Create gradle properties
        env:
          SIGNINGKEYID: ${{ secrets.SIGNINGKEYID }}
          SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}
          SONATYPEPASSWORD: ${{ secrets.SONATYPEPASSWORD }}
          SONATYPEUSER: ${{ secrets.SONATYPEUSER }}
        run: echo -e "signing.keyId=$SIGNINGKEYID\nsigning.password=$SIGNINGPASSWORD\nsigning.secretKeyRingFile=$HOME/.gradle/secrets.gpg\nsonatypeUsername=$SONATYPEUSER\nsonatypePassword=$SONATYPEPASSWORD" > $HOME/.gradle/gradle.properties

      - name: Build with Gradle
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=true"
        run: ./gradlew build :publishIntershopMvnPublicationToMavenRepository -s --scan

      - name: Post Build
        run: rm -f $HOME/.gradle/gradle.properties && rm -f $HOME/.docker/config.json
